create table
    public.test (
        id bigint generated by default as identity,
        created_at timestamp
        with
            time zone null default now (),
            constraint test_pkey primary key (id)
    ) tablespace pg_default;

alter publication supabase_realtime add table test;